server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://124.221.80.137:3306/blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 508816739
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #??springboot???swagger2???
  # rabbitmq配置
  rabbitmq:
    host: 124.221.80.137
    port: 5672
    username: admin
    password: 508816739
    listener:
      simple:
        retry:
          enabled: true
          # 重试间隔时间
          initial-interval: 3000
          # 最大重试次数
          max-attempts: 3
  # 邮箱配置
  mail:
    host: smtp.qq.com
    # 用户名
    username: 508816739@qq.com
    # 授权码
    password: dbcafhyonqrfbjid
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
  data:
    redis:
      host: 124.221.80.137
      port: 6379
      password: 508816739

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  # 实体类扫描包路径
  type-aliases-package: com.he.entity
  global-config:
    db-config:
      # 数据库表前缀
      table-prefix: t_
  configuration:
    # sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true

## JWT ??
Jwt:
  #jwt????
  secretKey: asdfghjklweqet
  #jwt ????? ????
  ttlMillis: 86400
#oos配置
oss:
  # 密钥
  accessKey: FCP6Metm7UYYCTbKsPsIR4staOzeSFs81Cel198V
  # 密钥
  secretkey: 96eeE0IKzT--lnJtXw0T5NhV-KMgMXNKBZETURNc
  # 存储空间名
  bucketName: ink-blog007
  # 区域名
  region: huadong
  # 外链域名
  url: http://s21ql62im.hd-bkt.clouddn.com
# 上传策略
upload:
  strategy: oss

# 博客链接 域名后面要加/
blog:
  url: localhost:8989/index.html/#/、
# 线程池配置
thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
minio:
  access-key: root
  secret-key: 508816739
  bucket-name: blog
  endpoint: http://124.221.80.137:9000
